apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: csm-x100-fconfig-ds-<Version>
  namespace: x100-operator-resources
  labels:
    app: csm-x100-fconfig-ds
spec:
  selector:
    matchLabels:
      app: csm-x100-fconfig-ds
  template:
    metadata:
      labels:
        app: csm-x100-fconfig-ds
    spec:
      imagePullSecrets:
      - name: eks-pull-secret
      containers:
      - name: csm-x100-fconfig
        image: #<ToBeReplaced with fconfig container image>
        imagePullPolicy: Always
        securityContext:
          privileged: true
        lifecycle:
          preStop:
            exec:
              command: ["/bin/bash", "-c", "rm -rf /var/tmp/lassenconfig /var/tmp/lassenconfig_common /var/tmp/lassenconfig_devices /var/tmp/device_specific_configs_available /var/tmp/vf-count.conf /var/tmp/fconfig-state.conf"]
        env:
          - name: DYNAMICCONFIG_PODNAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: ApplyConfiguration
            value: apply_configuration.conf
          - name: CompressedConfig
            value: configfiles.tar.gz
        volumeMounts:
        - mountPath: /var/lib/firmware/qcom/lassen
          name: hostpath-privileged
        - mountPath: /var/tmp
          name: csm-fconfig-status
        - mountPath: /etc/configmap
          name: x100-dyn-config
      volumes:
      - name: hostpath-privileged
        hostPath:
          path: /var/lib/firmware/qcom/lassen
      - name: csm-fconfig-status
        hostPath:
          path: /tmp
          type: Directory
      - name: x100-dyn-config
        configMap:
          name: x100-dyn-config
      nodeSelector:
        kubernetes.io/hostname: #<Node-Name>  ##For Single node config Update
        #qualcomm.com/x100.swversion: "default"  ##For all the Nodes running default SW version
