#
# Splane time sync config file
#

[global]

# Specifies if PTP is supported, Enable:1 Disable:0 Default: 0. Any other value is invalid
ptp_supported = 0

# Specifies if SYNCE is supported, Enable:1 Disable:0 Default: 0. Any other value is invalid
synce_supported = 0

# Specifies if GNSS is supported, Enable:1 Disable:0 Default: 0. Any other value is invalid
gnss_supported = 1

[clock]
# After the holdover interval is elapsed the clock transitions to holdover out of spec (freerun). Default: 1000
#holdover_interval = 1000

[ptp]
# PTP profile, default: 1
# 1: g8275.1 - ITU-T G8275.1
# 2: g8275.2 = ITU-T G8275.2
profile = 1

# Clock type to use for ptp on this system, default: 1
# 1: t-gm - telecom grandmaster,
# 2: t-bc - telecom boundary clock
# 3: t-sc - telecom timing slave clock
clock_type = 1

# A flag indicating if PTP should be started only after SyncE lock is acheived, default: false
start_after_synce_lock = 0

# Specifies the time, in milliseconds, to wait for SyncE lock, before starting PTP.
# Applicable only in case start_after_synce_lock is set to 1. Default 6000
#time_to_wait_for_synce_lock = 6000

[port_1]
#interface = eth00

# Announce receipt timeout. Default for G.8275.1 Profile is 6 and for G.8275.2 Profile is 2. Default: 0
#port_announce_receipt_timeout = 6

# Log Announce interval. Default for G.8275.1 Profile is -3 and for G.8275.2 Profile is 0
#port_announce_interval = -3

# Log Sync interval. Default for G.8275.1 Profile is -4 and for G.8275.2 Profile is -6
#port_sync_interval = -4

# Delay asymmetry calibration to be applied to time measurements. This is in <sec.ns> format.
#port_asymmetry = 0

[platform]

#TOD source:
# 1 - Uart
# 2 - PCIe
# 3 - NOT SUPPORTED
# 4 - Chrony
tod_src = 2

# SMA IO Expander Config
# Default is 0 - Config A1
# 0 - configuring SMA1 to 10MHz IN and SMA2 to 1PPS IN (Config A1)
# 1 - configuring SMA1 to GNSS RF IN and SMA2 to 1PPS OUT (Config B)
# 2 - configuring SMA1 to 1PPS IN and SMA2 to 1PPS OUT (Config C)
# 3 - configuring SMA1 to GNSS RF IN and SMA2 to 10MHz OUT (Config D)
# 4 - configuring SMA1 to N/A and SMA2 to 1PPS IN (Config C2)
i2c_sma_config = 0

# A flag indicating whether x100 should publish GNSS data to L2 using MHI
# Enabling this feature is valid only if tod_src = 1 (UART is TOD source)
# and if SMA Config is set to Config B or D (i2c_sma_config = 1 or 3)
# Default is 0 (Disable)
# 0 - Disable
# 1 - ZDA only
# 2 - All NMEA
publish_gnss_msgs = 0

# Publish PTP announce messages to L2 side
# Interval of 0 seconds will disable the feature
# Default is 0 - disable
ptp_announce_publish_interval = 0
# Target IP address on the L2 side
#ptp_announce_publish_l2_ip = "192.200.100.0"
# Port number for sending the announce message to L2, Default: 320
#ptp_announce_publish_port = 320

[gnss]
# Clock Class when GNSS is stable. Default: 6
#clock_class_stable = 6

# Clock Class when GNSS is in holdover. Default: 7
#clock_class_holdover = 7

# Clock Class when GNSS is in free-run (degraded and out of specified holdover period/range). Default: 248
#clock_class_freerun = 248
