apiVersion: kmm.sigs.x-k8s.io/v1beta1
kind: Module
metadata:
  name: csm-x100-kmm
  namespace: x100-operator-resources
spec:
  moduleLoader:
    container:
      modprobe:
        moduleName: csm_dp
      kernelMappings:
        - regexp: '^.+$'
          containerImage: #ToBeReplacedbyController
          build:
            buildArgs:
            - name: LONG_AU_TAG
              value: #ToBeReplacedbyController
            - name: DTK_AUTO
              value: #ToBeReplacedbyController
            - name: DTK_SRC
              value: #ToBeReplacedbyController
            dockerfileConfigMap:
              name: #ToBeReplacedbyController
              namespace: x100-operator-resources
  imageRepoSecret:
    name: eks-pull-secret
  selector:
    qualcomm.com/x100.present: "true"
