apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: csm-x100-device-plugin
  namespace: x100-operator-resources
  labels:
    app: csm-x100-device-plugin
spec:
  selector:
    matchLabels:
      app: csm-x100-device-plugin
  template:
    metadata:
      labels:
        app: csm-x100-device-plugin
    spec:
      securityContext:
        runAsUser: 0
      imagePullSecrets:
      - name: csm-x100-eks-pullsecret
      containers:
      - image: #"<Replace with Csm-Device Plugin image>"
        args:
        - --device
        - |
          name: qti-csm
          groups:
            - paths:
                - path: /dev/csm*
        - --vfcount
        - |
          count: 1
        name: csm-x100-device-plugin-container
        securityContext:
          runAsUser: 0
          privileged: true
        volumeMounts:
        - name: device-plugin
          mountPath: /var/lib/kubelet/device-plugins
        - name: dev
          mountPath: /dev
        - name: sys-dev
          mountPath: /sys/bus/pci/devices
      volumes:
      - name: device-plugin
        hostPath:
          path: /var/lib/kubelet/device-plugins
      - name: dev
        hostPath:
          path: /dev
      - name: sys-dev
        hostPath:
          path: /sys/bus/pci/devices
          type: Directory
      nodeSelector:
        qualcomm.com/x100.present: "true"
