apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csm-x100boot-eks-pvc
  namespace: x100-operator-resources
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 25Gi
  storageClassName: manual
