apiVersion: v1
kind: PersistentVolume
metadata:
  name: csm-x100boot-eks-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 25Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/var/lib/firmware/qcom/lassen"
