apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: csm-x100-eks-fwdaemonset
  name: csm-x100-eks-fwdaemonset
  namespace: x100-operator-resources
spec:
  selector:
    matchLabels:
      app: csm-x100-eks-fwdaemonset
  template:
    metadata:
      labels:
        app: csm-x100-eks-fwdaemonset
    spec:
      serviceAccount: csm-x100boot-eks-sa
      serviceAccountName: csm-x100boot-eks-sa
      securityContext:
        runAsUser: 0
        #privileged: true
      imagePullSecrets:
      - name: csm-x100-eks-pullsecret
      containers:
      - image: #"<Replace with Firmware pod image>"
        name: csm-x100-eks-fwcontainer
        imagePullPolicy: Always
        command: ["/sbin/init"]
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh", "-c", "systemctl stop csm-x100boot-ocp"]
        securityContext:
          runAsUser: 0
          privileged: true
        volumeMounts:
        - name: dev
          mountPath: /dev
        - name: x100-firmware
          mountPath: /var/lib/firmware/qcom/lassen
        - name: varlog
          mountPath: /var/log
        - name: sysfscgroup
          mountPath: /sys/fs/cgroup
      - image: registry.access.redhat.com/ubi8/ubi-minimal
        name: csm-x100-eks-fwlogs
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        args:
        - /bin/sh
        - -c
        - "tail -n+1 -F /var/log/x100_boot_ocp.log /var/log/ver_info.txt"
      volumes:
        - name: dev
          hostPath:
            path: /dev
        - name: sysfscgroup
          hostPath:
            path: /sys/fs/cgroup
            type: Directory
        - name: varlog
          emptyDir: {}
        - name: x100-firmware
          persistentVolumeClaim:
            claimName: csm-x100boot-eks-pvc
      nodeSelector:
        #Selector should reflect the nodes that have x100 card
        #at a later point
        qualcomm.com/x100.present: "true"
