apiVersion: qualcomm.com/v1
kind: X100ManagementPolicy
metadata:
  name: x100managementpolicy-v1
spec:
  swVersion: v1
  nodeSelectors:
  - <Node-Name> #ToBeReplaced
  x100Resources:
    firmware:
      repository: #<CIR registry URL>
      image: fwpod
      version: v1
      imagePullPolicy: Always
      imagePullSecrets:
      - eks-pull-secret
    hwManager:
      repository: #<CIR registry URL>
      image: hwmgr
      version: v1
      expRepository: #<CIR registry URL>
      expImage: exporter
      expVersion: v1
      imagePullPolicy: Always
      imagePullSecrets:
      - eks-pull-secret
    kModule:
      repository: #<CIR registry URL>
      image: kmodules
      version: v1
      tag: AU_LINUX_EMBEDDED_LE.LNXHOSTSW.2.0_TARGET_ALL.01.404.259
      dtkAutoImage: #<CIR registry URL>/<dtk-auto-image>
      dtkSrcImage: #<CIR registry URL>/<dtk-src-image>:v1
      imageRepoSecret: eks-pull-secret
    devicePlugin:
      repository: #<CIR registry URL>
      image: csmdp
      version: v1
      imagePullPolicy: Always
      imagePullSecrets:
      - eks-pull-secret
