apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  namespace: x100-operator-resources
data:
  fluentd.conf: |
    <source>
      @type tail
      path /var/log/containers/csm-x100hwmgr-daemonset-*_x100-operator-resources_csm-x100-hwmanager-logs3-*.log
      pos_file /var/log/x12-containers-hwmgr-logs1.log.pos
      tag X12-HwMgr-LOGS.*
      follow_inodes true
      read_from_head true
      <parse>
        @type none
      </parse>
    </source>

    <match X12-HwMgr-LOGS.**>
      @type stdout
    </match>
